# Generated by Django 2.2.16 on 2023-02-07 19:40

from django.db import migrations

INITIAL_TAG = (
    {'name': 'Завтрак', 'color': 'orange', 'slug': 'breakfest'},
    {'name': 'Обед', 'color': 'green', 'slug': 'lunch'},
    {'name': 'Ужин', 'color': 'purple', 'slug': 'dinner'},
)


def add_tags(apps, schema_editor):
    Tag = apps.get_model('recipes', 'Tag')
    for tag in INITIAL_TAG:
        new_tag = Tag(**tag)
        new_tag.save()


def remove_tags(apps, schema_editor):
    Tag = apps.get_model('recipes', 'Tag')
    for tag in INITIAL_TAG:
        Tag.objects.get(slug=tag.get('slug')).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_tags,
            remove_tags
        )
    ]
