# Generated by Django 2.2.16 on 2023-02-07 19:58

from django.db import migrations
from pathlib import Path


data = Path('ingredients.csv')


def add_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    with open(data, 'r') as csvfile:
        for ingredient in csvfile.readlines():
            ingredient = ingredient.rstrip().split(',')
            measurement_unit = ingredient[-1]
            name = ','.join(ingredient[:-1])

            Ingredient(name=name,
                       measurement_unit=measurement_unit).save()


def remove_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    with open(data, 'r') as csvfile:
        for ingredient in csvfile:
            ingredient = ingredient.rstrip().split(',')
            name = ','.join(ingredient[:-1])
            Ingredient.objects.get(name=name).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_add_tag'),
    ]

    operations = [
        migrations.RunPython(
            add_ingredients,
            remove_ingredients
        )
    ]
