# Generated by Django 2.2.16 on 2023-02-07 19:58

from django.db import migrations
from pathlib import Path
import csv


data = Path('ingredients.csv')


def add_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    with open(data, newline='') as csvfile:
        ingredients = csv.reader(csvfile, delimiter=',', quotechar='|')
        for ingredient in ingredients:
            Ingredient(name=ingredient[0],
                       measurement_unit=ingredient[1]).save()


def remove_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    with open(data, newline='') as csvfile:
        ingredients = csv.reader(csvfile, delimiter=',', quotechar='|')
        for ingredient in ingredients:
            Ingredient.objects.get(name=ingredient[0]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_add_tag'),
    ]

    operations = [
        migrations.RunPython(
            add_ingredients,
            remove_ingredients
        )
    ]
