# Generated by Django 2.2.16 on 2023-01-11 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodgram_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_in_shopping_cart', models.BooleanField(default=False, verbose_name=('is in shopping cart',))),
                ('is_favorited', models.BooleanField(default=False, verbose_name=('is in favorites',))),
                ('added_to_favorites', models.DateTimeField(auto_now_add=True, verbose_name=('added at',))),
                ('added_to_shopping_cart', models.DateTimeField(auto_now_add=True, verbose_name=('added at',))),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_favourites', to='foodgram_app.Recipe', verbose_name=('recipe',))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_recipes', to=settings.AUTH_USER_MODEL, verbose_name=('user',))),
            ],
            options={
                'verbose_name': ('Favorites',),
                'verbose_name_plural': ('Favorites',),
                'ordering': ['-added_to_favorites', '-added_to_shopping_cart'],
            },
        ),
        migrations.AddConstraint(
            model_name='favouriterecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favorite_recipe'),
        ),
    ]
