# Generated by Django 2.2.16 on 2023-01-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_app', '0002_auto_20230111_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(default='', max_length=20, verbose_name=('measurement_unit',)),
        ),
    ]
