# Generated by Django 2.2.16 on 2023-01-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_app', '0003_auto_20230111_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='count',
        ),
    ]
